name: Build FastAPI container

on:
  push:
    branches:
      - main

jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Build Docker Image
#         run: docker build -t fastapi-ubuntu .

  # run:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Run Docker Container
  #       run: |
  #         docker run -d -p 8000:8000 fastapi-ubuntu
  #       env:
  #         DOCKER_BUILDKIT: 1

