name: Build FastAPI container

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: env | sort
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USER }}/practice:first

# jobs:
#   build-with-docker:
#     name: Build with Docker
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: docker/setup-buildx-action@v3
#       - uses: docker/build-push-action@v5
#         with:
#           context: .
#           cache-from: type=gha
#           cache-to: type=gha,mode=max

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Build Docker Image
#         run: docker build -t fastapi-ubuntu .

  # run:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Run Docker Container
  #       run: |
  #         docker run -d -p 8000:8000 fastapi-ubuntu
  #       env:
  #         DOCKER_BUILDKIT: 1

